### ISSUE TITLE
CI Workflow failed

### ISSUE THREAD

**Issue by carl0shd** [jessety/encrypted-env#11]
Hi, i am using the config to decrypt env files in a Github CI Workflow but its not working.

```
- name: Decrypt env
        run: npx env-decrypt production
        env:
          ENV_KEY: ${{ secrets.ENV_KEY }}
          CI: true
```

The Workflow output is this:
<img width="640" alt="Screenshot 2023-02-04 at 4 29 10 PM" src="https://user-images.githubusercontent.com/8359234/216790324-1c6c8623-fb98-4819-831a-e09db964cc22.png">
